baseURL = "/"
languageCode = "en-us"
relativeURLs = "true"
summaryLength = "10"
theme = "kross-hugo"
title = "justsoantsy.eth | Drag, NFT music, and art. "
[[menu.main]]
URL = "https://justsoantsy.com/shop"
name = "shop"
weight = ""
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "https://justsoantsy.com/blog"
name = "blog"
weight = ""
[params]
address = ""
author = "Leo M. Davis"
copyright = "Copyrighht &copy; 2022 |  [justsoantsy.com](https://justsoantsy.com)"
description = "This is meta description"
email = ""
google_analitycs_id = "Your ID"
home = "justsoantsy.eth"
logo = "/images/justsoantsy-2021-logo-white.png"
phone = ""
theme_color = "#8F00B3"
[params.contact]
enable = false
form_action = "info@justsoantsy.com"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.youtube.com/justsoantsy"
icon = "ti-youtube"
[[params.social]]
URL = "https://twitter.com/justsoantsy"
icon = "ti-twitter-alt"
